# Generated by Django 3.1.5 on 2021-03-02 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabalho', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(db_column='id_tarefa', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('data_realizacao', models.DateField(blank=True, db_column='data_realizacao', null=True)),
                ('tipo_tarefa', models.ForeignKey(blank=True, db_column='id_tipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipotarefa')),
                ('trabalho', models.ForeignKey(blank=True, db_column='id_trabalho', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trabalho.trabalho')),
            ],
            options={
                'db_table': 'tarefa',
                'managed': True,
            },
        ),
    ]
