# Generated by Django 3.1.5 on 2021-02-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipoatividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTarefa',
            fields=[
                ('id', models.AutoField(db_column='id_tipo_tarefa', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_tarefa',
                'managed': True,
            },
        ),
    ]
