# Generated by Django 3.1.5 on 2021-02-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tipotarefa'),
        ('trabalho', '0005_auto_20210202_0932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoAtividade',
        ),
    ]
