# Generated by Django 3.1.5 on 2021-02-01 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.AutoField(db_column='id_trabalho', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('data_inicio', models.DateField(blank=True, db_column='data_inicio', null=True)),
                ('data_entrega', models.DateField(blank=True, db_column='data_entrega', null=True)),
                ('nome_aluno', models.CharField(blank=True, max_length=255, null=True)),
                ('email_aluno', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('area', models.ForeignKey(blank=True, db_column='id_area', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.area')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(blank=True, db_column='id_tipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipo')),
            ],
            options={
                'db_table': 'trabalho',
                'managed': True,
            },
        ),
    ]
