# Generated by Django 3.1.5 on 2021-02-01 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho', '0002_auto_20210201_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalho',
            name='email_aluno',
        ),
        migrations.RemoveField(
            model_name='trabalho',
            name='nome_aluno',
        ),
    ]
