# Generated by Django 3.1.5 on 2021-02-02 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tipotarefa'),
        ('trabalho', '0004_tarefa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='tipo_atividade',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='tipo_tarefa',
            field=models.ForeignKey(blank=True, db_column='id_tipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipotarefa'),
        ),
    ]
