# Generated by Django 3.1.5 on 2021-02-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusuario',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='customusuario',
            table='usuario',
        ),
    ]
